#!/usr/bin/env python

# mkphplist: find all non-thumbnail images under the current directory,
# and generate a showpix.php with the appropriate image list.
# Copyright 2004 by Akkana Peck. 
# You may use and distribute this under the GPL.

import sys, os

contents = ''

# Try to get an image's size. Return width, height as strings.
def getthumbsize(imgname) :
    try :
        # First, get the thumbnail name
        parts = os.path.splitext(imgname)
        fp = os.popen("identify " + parts[0] + "T" + parts[1])
        s = fp.readline()
        fp.close()
        if not s :
            return 0, 0
        sizes = s.split()[2].split("x")
        return sizes[0], sizes[1]

    except :
        return None, None

def mkline(imgname) :
    global contents
    if imgname in contents :
        print "Skipping", imgname
        return

    imgname = imgname.strip()
    if imgname[0:2] == "./" :
        imgname = imgname[2:]
    w, h = getthumbsize(imgname)
    if w != 0 and h != 0 :
        sizestr = ", " + w + ", " + h
    else :
        sizestr = ""
    contents += "    array (\"" + imgname + "\", \"\"" + sizestr + "),\n"

# If the first argument doesn't have a ., or ends in .html or .php,
# use that as the filename. Otherwise, use stdout.
outfile = None
if len(sys.argv) > 1 and ('.' not in sys.argv[1] or
                          sys.argv[1].endswith('.php') or
                          sys.argv[1].endswith('.html')) :
    outfile = sys.argv[1]
    sys.argv = sys.argv[1:]

# Find the image files to use.
imgfiles = []
if len(sys.argv) <= 1 :
    fp = os.popen("find . -name \"*.jpg\" | grep -v T.jpg")
    while True :
        line = fp.readline()
        if not line : break
        imgfiles.append(line)
else :
    imgfiles = sys.argv[1:]

# Okay, we've parsed the arguments. Start doing stuff.
if outfile :
    outfp = open(outfile, 'w')
else :
    outfp = sys.stdout

contents += "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"

contents += "\n<?php\n"
contents += "  $title = \"Images\";\n"
contents += "  $preamble = \"\";\n"
contents += "  $pixlist = array(\n"

for fil in imgfiles :
    mkline(fil)

contents += "  );"

contents += 'require($_SERVER["DOCUMENT_ROOT"] . "/software/gallerypage-base.php");\n'
contents += "?>\n"

print >>outfp, contents

